version: "3"

services:
  postgis:
    container_name: postgis
    image: postgis/postgis
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DB=postgis
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

networks:
  app-network:
    driver: bridge
