[tool.poetry]
name = "python-falcon-api"
version = "0.1.0"
description = ""
authors = ["João Victor"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
